"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/2/Tv34.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/2/Tv35.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/2/Tv36.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/2/Tv37.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/2/Tv89.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/2/Tv90.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/3/11k.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/3/13k.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/3/14k.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/3/1k.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/3/2k.jpg" -bg bg -fg fg
"../bin/TrainingSampleMaker.exe" "../Images/New Images From Anna/3/4k.jpg" -bg bg -fg fg